.circleci/config.yml, command-snapshot.json, package.json, src/help/sfCommandHelp.ts, src/help/sfHelp.ts, yarn.lock
@W-9791511@ add custom help class
=> feat: add help class to display additional cmd help

package.json, yarn.lock
=> fix: bump oclif/core and sf-plugins-core version

.circleci/config.yml
=> fix: install sf-release for maybe-halt

command-snapshot.json, package.json, yarn.lock
=> chore: 0.0.47

package.json, yarn.lock
=> fix: revert inquirer dep that references github url

package.json, yarn.lock
=> fix: bump deps for latest-rc

package.json, yarn.lock
Bundle `@oclif/plugin-update` with sf
@W-10126254@
=> chore: include plugin-update

.circleci/config.yml, command-snapshot.json
=> chore: remove test-sf-includsion - no longer needed

package.json
Resolve path length issues related to `@oclif/config` and `@oclif/command`
=> chore: add resolutions

command-snapshot.json, package.json, yarn.lock
Adds the plugin-info command to display release notes on the command line
Do not merge this until https://github.com/salesforcecli/plugin-info/pull/33 and https://github.com/salesforcecli/plugin-info/pull/32 are merged.
[@W-10260114@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10260114)
- Pull branch
- View help `./bin/run info releasenotes display --help`
- View notes `./bin/run info releasenotes display -v 1.3.0`
- Test alias `./bin/run whatsnew`
=> Add plugin info

package.json, yarn.lock
Adds `@oclif/plugin-autocomplete`
=> chore: add plugin-autocomplete

command-snapshot.json, package.json, yarn.lock
Bumps @oclif/plugin-update to 3.0.0
=> chore: bump @oclif/plugin-update

package.json
Pack and upload `.xz` tarballs
=> Pack and upload .xz tarballs

package.json, yarn.lock
=> chore: bump plugin-generate

.circleci/config.yml
=> chore: use contexts

.circleci/config.yml, package.json
=> fix: add cli-release context to windows package job for signing key

.circleci/config.yml, command-snapshot.json
Adds CircleCI job to test that the command-snapshot hasn't changed
@W-11048086@
=> chore: add verify-no-snapshot-changes job

package.json, yarn.lock
Adds `@salesforce/plugin-trust` as a bundled plugin
@W-11540140@
=> chore: add @salesforce/plugin-trust

package.json
Bump plugin-functions to the latest version. This version contains documentation updates.
N/A
=> chore(functions): bump to 1.13.5

.github/workflows/announceRC.yml
automate slack posts after RC builds
you like the slack post
@W-11586904@
=> ci: announce rc builds on slack

command-snapshot.json, package.json, src/hooks/pluginsPreinstall.ts, yarn.lock
**DEPENDS ON**: https://github.com/salesforcecli/plugin-release-management/pull/529
Adds an oclif hook to verify a plugin signature before installing it.
signature verification hook:  https://github.com/salesforcecli/plugin-trust/blob/main/src/hooks/verifyInstallSignature.ts
`sf` will verify a plugin signature when trying to install one using the `plugins install` command.
If the plugin is signed `sf` will print `Successfully validated digital signature for <plugin>` and continue with the install, if it  isn't signed then it will ask the user if they want to continue.
`yarn build`
`./bin/run plugins install @salesforce/plugin-user` signed plugin, should confirm valid signature
`./bin/run plugins install @mshanemc/plugin-streaming` --> unsigned plugin, will prompt for confirm
- ✅  This …
=> feat: verify plugin signature before installing it

.github/workflows/justNut.yml, .github/workflows/makePRforRC.yml, .github/workflows/rcTagAndRelease.yml
Switches the account used for GHA CI.
@W-9073995@
=> chore: change env var

.github/workflows/justNut.yml
retries on just-nuts
@W-12084293@
=> test: just nuts retry like normal nuts

command-snapshot.json, src/hooks/incomplete.ts
Emits a warning message when the command entered is a partial command and there is only one match for the command
@W-12212675@
=> fix: message on 1 partial match

command-snapshot.json, package.json, yarn.lock
[skip-validate-pr] 
adds 
`plugin-data`
`plugin-community`
`plugin-custom-metadata`
=> chore: add plugin-data,community,custom-metadata

package.json
adds the 3 new plugins to pinnedDeps, with the correct title to release as latest-rc
=> Release PR for 1.61.1

.github/workflows/just-nuts.yml, .github/workflows/rcBuild.yml
Adds missing repos to our just-nuts workflow
=> Add to just-nuts.yml

package.json
=> chore: fix package name

.github/workflows/makePRforRC.yml, package.json, src/cli.ts, yarn.lock
Building 1.62.1 [skip-validate-pr]
=> Release PR for 1.62.1

.github/workflows/makePRforRC.yml
Adds the intended release channel for https://github.com/salesforcecli/plugin-release-management/pull/694
[@W-12599588@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12599588)
=> Add release-channel

.github/workflows/just-nuts.yml, package.json
Add plugin-dev as a jit plugin
Add plugin-dev to just-nuts.yml
=> feat: add plugin-dev as jit plugin

.github/workflows/just-nuts.yml
remove plugin-generate
add plugin-templates
=> chore: fix just-nuts.yml

package.json, yarn.lock
=> fix: remove functions as a bundled plugin

.github/workflows/v2-beta.md
=> docs: v2 beta [no ci]

package.json
increase the number of CLI artifact versions stored to 140
@W-00000000@
=> chore: increase version limit

.github/workflows/v2-beta.md
_Describe the feature with use cases or bug details. Interesting/complex design choices or weird workarounds should be documented in the code but can be included here instead if there is a valid reason it shouldn't be in the code._
_How do you know this change is successful? What is the scope of this change? What tests test the criteria (or why no tests)?_
_The Acceptance Criteria can be copied from the work item if they exist there but it is useful to have on the PR when reviewing the code._
=> add CI instructions

.github/workflows/create-github-release.yml
Removes change logs since they are not needed. See https://github.com/salesforcecli/sfdx-cli/pull/1267
[@W-13660199@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13660199)
=> Remove change logs

.github/workflows/create-github-release.yml
Removes change logs since they are not needed. See https://github.com/salesforcecli/sfdx-cli/pull/1267
[@W-13660199@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13660199)
=> V2 branch: remove change logs

scripts/preinstall.js
Adds a note to the migration documentation
NOTE: This page is not yet live. We will need to validate the url is correct as soon as it is live.
=> Add link to docs

.github/workflows/v2-beta.md
- Gives a context on why an uninstall is needed
- Gives an example of the error you'd see with `npm` installs
=> Add more details on cli collisions

bin/run
remove vestigial `overrides` property
=> chore: remove overrides

.github/workflows/promote.yml
[Promotion is failing](https://github.com/salesforcecli/cli/actions/runs/5672167909/job/15371627537#step:5:44)
I need to see which key it is here: [debug(`error on ${key}`, error)](https://github.com/oclif/oclif/blob/18f315687dd1da132a0a766efbdd60eedf542fba/src/version-indexes.ts#L57-L58)
=> Debug on oclif promote

package.json
add devops center plugin (1.0.0-beta.2) as JIT
=> chore: add devops center plugin as JIT

.github/workflows/create-cli-release.yml, .github/workflows/test.yml
upload to stampy bucket after building win installers
[@W-9805654@](https://gus.lightning.force.com/a07EE000000xaPYYAY)
=> test: cause upload

src/hooks/incomplete.ts
Prompt users to select matching command even when partial command yielded only one match
@W-14196793@
=> feat: prompt when single partial command match

package.json, yarn.lock
=> chore: bump plugin-data

.github/workflows/just-nuts.yml
https://github.com/salesforcecli/cli/actions/runs/9288293177/job/25559966713
=> ci: disable package1 nuts

package.json, yarn.lock
bump some devDeps, including PRM for the fix (and better error logs) for https://github.com/salesforcecli/cli/actions/runs/9279216924/job/25531425524
=> chore: bump dev-deps

package.json, yarn.lock
=> fix(deps): core8

.github/workflows/jit-install-smoke.yml
updates the artifact action version from v3 to v4.
to fix a bunch of warnings
=> ci: update artifact action version

README.md, package.json, yarn.lock
=> Release PR for 2.63.8 as latest

.github/workflows/promote-rc-to-latest.yml
CTC API is fixed, reenable ctc
[@W-17694024@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17694024)
=> W-17694024 enable ctc

package.json
Adds https://github.com/salesforcecli/plugin-flow to the Just In Time (JIT) install list
[@W-18327026@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18327026)
=> W-18327026: dd plugin-flow to jit list

LICENSE.txt, README.md, package.json, src/hooks/preparse.ts, yarn.lock
The CLI has slightly different scripts than our plugins and libraries. I needed to make sure the latest `wireit` was in stalled (through dev-scripts)
https://github.com/salesforcecli/github-workflows/pull/140
Related to [@W-18302796@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18302796)
=> W-18302796: bump wireit, fix types

.github/workflows/just-nuts.yml, package.json
add plugin-agent to JIT list and run the NUTs as part of the release
@W-18350787@
=> fix: add plugin-agent to JIT list - W-18350787
