.circleci/config.yml

Skip release builds when merging PRs from `dependabot-automerge`

chore: skip ci for dependabot automerges

---

package.json
yarn.lock

This updates the `sf` cli to use [our Inquierer.js fork](https://github.com/salesforcecli/Inquirer.js).
Once https://github.com/SBoudrias/Inquirer.js/pull/1052 is merged and released we can switch back to using the normal Inquirer.js library by reverting this change and updating the dependencies in our plugins.
@W-9670281@

fix: update inquirer dep to our fork

---

.circleci/config.yml
package.json
yarn.lock

This now verifies that the `stable-rc` promotion happened correctly after a release instead of `stable` which doesn't happen on a normal release.

feat: verify promote for stable-rc channel

---

command-snapshot.json
package.json
yarn.lock

This bumps functions to 1.4.2 which contains the migration from axios to jsforce as our http library.
The customer is able to use the functions plugin with their proxy/vpn
@W-10203652@

chore: bump plugin-functions to 1.4.2

---

package.json
yarn.lock

Bumps plugin-functions to 1.4.3
NA
NA

chore: bump plugin-functions to 1.4.3

---

.circleci/config.yml

Updates the circle config to generate the latest-rc PR/branch directly after releasing a new version. The resulting branch will be the "release" branch for the coming week until it's merged into main
NA
NA

chore: update circle config

---

.circleci/config.yml
package.json

Bumps the node and macos images used for packing the macos and windows installers in order to be consistent with sfdx.

chore: bump macos and node images

---

package.json
schemas/@sf/drm/hooks/sf-deploy.json
schemas/@sf/env/env-open.json
yarn.lock

- Removes `sfdx-faye` from the dependency tree
```
~/repos/salesforcecli/cli [1.11.1] : yarn why sfdx-faye
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "sfdx-faye"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "@salesforce/templates@53.1.0" is incompatible with requested version "@salesforce/templates@^52.0.0"
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.87s.
```
```
~/repos/salesforcecli/cli [1.11.1] : grep sfdx-faye yarn.lock | wc -l
0
```

chore(latest-rc): bump to 1.11.1

---

bin/run

Suppresses `MaxListenersExceededWarning` in the same way that [sfdx does](https://github.com/salesforcecli/sfdx-cli/blob/main/bin/run#L6-L12)
`npm install -g @salesforce/cli@dev`
@W-10514668@

chore: set max listeners

---

package.json
src/hooks/preupdate.ts

Adds a preupdate hook that warn users if they're attempting to update a version of sf that's bundled with sfdx
```
~/repos/oclif/plugin-update [mdonnalley/specify-version] : sf update -v 1.12.0
›   Warning: Running sf update will have no effect since you are using a version that was installed by sfdx. Please use sfdx update instead.
```

chore: add preupdate hook

---

package.json
src/help/sfHelp.ts

Automatically dim command names in help output

Automatically highlight command names in help

---

package.json
yarn.lock

Building latest-rc [skip-validate-pr]
Merging this will revert `plugin-functions` so as to not include in the `env log` command when `latest-rc` is promoted to `latest` on Wednesday.

Release v1.25.2 as latest-rc

---

package.json
yarn.lock

Adds `@salesforce/schemas` to yarn resolutions so that we always get the newest version
These resolutions get bumped automatically in [plugin-release-management](https://github.com/salesforcecli/plugin-release-management/blob/main/src/commands/cli/latestrc/build.ts#L68)
All builds pass
Should not need testing
- [NA] This change has been approved by the CLI Review Board or approval isn't required. Anything that adds/changes/deletes commands, flags, output, or json output has to be reviewed.
- [NA] Does this follow the [deprecation policy](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_deprecation.htm)?
[W-11048751](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11048751)

Add schemas to yarn resolutions

---

src/hooks/incomplete.ts

If the user enters a partial command and there's only one match, then automatically run that command

feat: run command match when only one exists

---

package.json
yarn.lock

Bumps  @sf/functions to 1.13.4
This releases --json flag fixes
This change is largely a refactor of existing --json work but fixes the help output and solidifies the command schema.
N/a
N/a

chore(deps): bump @sf/functions to 1.13.4

---

command-snapshot.json
package.json
schemas/@sf/deploy-retrieve/retrieve-metadata.json
schemas/@sf/env/env-create-scratch.json
schemas/@sf/env/env-resume-scratch.json
schemas/@sf/login/login.json
yarn.lock

Bumps the following plugins
- plugin-deploy-retrieve: support metadata format in `retrieve metadata`
- plugin-env: dependency bumps
- plugin-login: dependency bumps
- plugin-generate: dependency bumps

Bump dependencies

---

package.json

This repository currently uses Yarn v1, however since no Yarn version is defined, if I run newer `yarn` locally it auto-migrates the repository to Yarn v3's new style lockfile and configuration.
Until such time as this project is migrated officially (which likely depends on Dependabot supporting Yarn 2/3), the Yarn v1 should be specified explicitly in `package.json`.
GUS-W-11739370.

chore: explicitly set yarn v1 as the packageManager

---

package.json
yarn.lock

Updates `@salesforce/plugin-functions` to 1.14.1. For details see:
https://github.com/salesforcecli/plugin-functions/blob/main/CHANGELOG.md#1141-2022-09-28
https://github.com/salesforcecli/plugin-functions/compare/v1.14.0...v1.14.1
https://github.com/heroku/sf-functions-core/compare/v0.4.0...v0.4.1
These changes have been validated downstream in https://github.com/salesforcecli/plugin-functions and https://github.com/heroku/sf-functions-core. For manual verification, these changes affect `sf generate function` and `sf run function start` in subtle ways, so those should continue to work.
[W-11543492](https://gus.my.salesforce.com/one/one.app#/alohaRedirec …

Update @salesforce/plugin functions to 0.14.1

---

package.json
yarn.lock

Bumps the dependency on @heroku/functions-core to update the JavaScript/TypeScript function templates which no longer require the dependency on `sf-fx-sdk-nodejs` since the types present in that module have been moved into `@heroku/sf-fx-runtime-nodejs`.
* Functions generated by the CLI now use an explicit dependency on `@heroku/sf-fx-runtime-nodejs` 
* TypeScript functions generated by the CLI no longer contain a dependency on `sf-fx-sdk-nodejs`
* Types used in the TypeScript function template are imported from `@heroku/sf-fx-runtime-nodejs` 
* Warnings about changing the`@heroku/sf-fx-runtime-nodejs` dependency to be explicit are issued for previously generated function projects that still use the "implicit" version of the runtime
* Existing functions that use the "implicit" version of …

chore: bump plugin function from 1.14.2 to 1.14.4

---

package.json
yarn.lock

* Bumps the Java Function Runtime version to 1.1.3
* Fixes a bug in the Java Function template which prevented the templated unit tests from compiling
List of changes: https://github.com/salesforcecli/plugin-functions/compare/1.17.0...1.17.4
The Function Runtime change is simply a version bump.  The CNB has gone through a separate build/QA pipeline process.  The CLI just needs to use that new version.
The Java Function template fix was tested manually to verify that after creating a new templated project you can:
* run the unit tests
* start the function 
[@W-12157391@](https://gus.lightning.force.com/a07EE00001FgZMwYAN)

chore: bump plugin function from 1.17.0 to 1.17.4

---

package.json

The last release GHA did not trigger after merging, I think it might have been because I had a "don't run ci" commit tag on a trivial commit in it. Testing without.

Release PR for 1.62.2

---

.github/dependabot.yml
package.json

dependabot config won't bump plugins (oclif or salesforcecli) since build scripts do that.

chore: let builds scripts update plugins

---

.github/workflows/automerge-dependabot.yml

Adjusting dependabot cron to prevent collisions with `nightly` automerge

chore: adjust crons

---

.github/workflows/create-github-release.yml
.github/workflows/validate-pr.yml

ci: prereleases can have slashes in their branch names

---

.github/workflows/make-pr-for-release.yml

Adds an `--empty` flag for creating an empty release PR. Useful for creating a PR to push changes to later.
[@W-13082275@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13082275)

Empty release flag

---

.github/workflows/create-cli-release.yml

Removes `docker-build-*` from needs until v2 is GA

Remove docker builds from needs until v2 GA

---

package.json

Now that we have `nightlies` we need to increase the number of versions that we keep on the version index. 

chore: increase index because nightlies

---

.github/workflows/make-pr-for-nightly.yml
.github/workflows/make-pr-for-release.yml
.github/workflows/v2-make-pr-for-nightly.yml
scripts/post-install-release-notes.js
src/hooks/display-release-notes.ts

Checks `SF_` env vars for hiding release notes, updates github actions
Related to: https://github.com/salesforcecli/plugin-info/pull/422
@W-13171024@

chore: use SF_ for hiding release notes

---

package.json

Updates the url for the sf v2 release notes. A draft already exists here https://github.com/forcedotcom/cli/blob/01284fb16a955d9a15b86307a04aad1c9db3ee80/releasenotes/README.md

Update release notes url

---

.github/workflows/promote.yml

Removes a check for docker promotions to allow sf v2 to promote

remove check for v2 GA

---

.github/workflows/make-pr-for-release.yml

Passes along the `--empty` boolean to https://github.com/salesforcecli/plugin-release-management/blob/main/src/commands/cli/release/build.ts#L155

chore: pass along --empty

---

package.json
src/hooks/prerun.ts

Adds prerun hook that will warn customers about user-installed plugins that differ from the version specified by sf. Warnings will only appear for the plugin that owns the command being run.
```
›   Warning: Plugin @salesforce/plugin-custom-metadata (2.2.0) differs from the version specified by sf (2.1.41)
```
@W-14086486@

feat: add version diff prerun hook

---

.github/workflows/automerge-nightly-pr.yml

The new JIT installs on windows take a long time and the automerge has been reaching it max retries

chore: increase automerge tries

---

package.json

Remove `@oclif/core` from pinnedDependencies until https://github.com/salesforcecli/cli/pull/1094 is merged

chore: remove @oclif/core from pinnedDeps

---

test/cli.test.ts

Removes `VersionCommand` assertion, which is not needed and needs to be removed before https://github.com/oclif/plugin-version/pull/269 can be merged
@W-14268190@

test: remove plugin-version assertion

---

src/hooks/incomplete.ts

hides hidden commands from the `incomplete_command` hook
e.g.
```
➜  sf package version      
? Which of these commands do you mean 
package version list                List all package versions in the Dev Hub org. 
package version promote             Promote a package version to released. 
package version report              Retrieve details about a package version in the Dev Hub org. 
❯ package version retrieve            Retrieve package metadata for a specified package version. 
package version update              Update a package version. 
package version create              Create a package version in the Dev Hub org. 
```
`package version retrieve` should not appear in this list because the command is hidden
the command doesn't appear
build, and run with `./bin/run.js …

chore: filter out ignored commands from search

---

src/flags.ts

makes `--dev-debug` to set `SF_LOG_LEVEL=trace` if it's not set.
to get debug logs from oclif and logging output we need to set `--dev-debug` and `SF_LOG_LEVEL` env var
only `--dev-debug` is required. The default log level is `trace` so that all logger output is included.
@W-14375066@

fix(debug): set default log level

---

package.json

`sf-plugins-core` and `oclif/core` were dropped from `pinnedDependencies` just before we released their latest major versions to avoid them being bumped before the ESM migration branch was merged. Now that it has been merged, we can add them back to `pinnedDependencies`

fix: add sf-plugins-core and oclif/core back to pinnedDeps

---

scripts/verify-promote

Minor changes to the `promote-verify` script. It is failing today
https://github.com/salesforcecli/cli/actions/runs/6723303590/job/18276144568#step:4:166

chore: promote-verify changes

---

.github/workflows/make-pr-for-nightly.yml
.github/workflows/make-pr-for-release.yml
.github/workflows/update-docker-node-version.yml
dockerfiles/update-docker-node-version.cjs

Needed to ensure the docker update steps were in the same `job` so that the changes were pushed to the branch created by the previous steps. 
Swapped `got` for `exec` to eliminate the need for a `yarn install`. 
[@W-14338799@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14338799)

chore: swap got, move docker update to same job

---

.github/workflows/create-cli-release.yml
.github/workflows/test.yml

I was trying to take advantage of `input` default on a workflow_call. However, apparently if a Repository Variable is not set, it still gets passed in as an empty string so the default is not used... This PR is explicit about the fallback (like we are everywhere else)
Example: https://github.com/salesforcecli/cli/actions/runs/6788841412/job/18455019175#step:1:47

chore: empty var does not invoke input default

---

.github/workflows/create-github-release.yml

The GHA `actions/create-release@v1` has been deprecated for a while. The PR replaces that action with a similar action
[@W-14488760@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14488760)
- PR: https://github.com/salesforcecli/cli/pull/1349
- Create release action: https://github.com/salesforcecli/cli/actions/runs/7038698855/job/19156176923#step:4:3
- Release: https://github.com/salesforcecli/cli/actions/runs/7038703648/job/19156196911#step:7:20
- Npm view dist-tags: 
```json
{
"latest": "2.19.8",
"latest-rc": "2.20.6",
"nightly": "2.21.1",
"beta": "2.0.0-beta.74",
"legacy": "1.86.7-legacy.0",
"dev": "2.20.6-dev.0", <-- yay
"qa": "2.16.2-qa.0",
"esm": "2.17.1-esm.0",
"cjs": "2.13.2-cjs.1"
}
```

Replace actions/create-release@v1

---

.github/workflows/create-github-release.yml
README.md
package.json
src/hooks/incomplete.ts
test/cli.test.ts
yarn.lock

Bumps dev-scripts and cleans up a few things
- Dev-scripts bump changes a lot of dev deps. Minor changes needed to pass tests
- Dev-scripts bump adds `link-check`. Updates `plugin-marketplace` to fix broken link
- Ran `oclif readme` (to pass `link-check`)
- Adds a `readme` script with the [flags we used in PRM](https://github.com/salesforcecli/plugin-release-management/blob/4de29e54def36cc73a486bc0527a555caa7302f0/src/commands/cli/release/build.ts#L194) 
- Sha of `ncipollo/release-action` used instead of Release version

dev-scripts bump

---

.github/workflows/just-nuts.yml

These have been flakey for a while, ignoring for now since we have not been able to replicate the error and have not received any external reports of this failing.

Ignore plugin-dev nuts on windows

---

package.json
src/hooks/incomplete.ts
yarn.lock

use new sf-plugins-core at the top-level
adjusts the incomplete command prompter stuff 
[@W-13801582@](https://gus.lightning.force.com/a07EE00001WgAQLYA3)

fix(deps): plugins-core 7

---

package.json

Add `examplePlugin` to `oclif` config so that plugin-plugins can show it in help instead of `myplugin`
```
EXAMPLES
Install a plugin from npm registry.
$ sf plugins install @salesforce/plugin-packaging
```

chore: add example plugin

---

package.json

we're using a beta release of templates in plugin-templates.  Resolutions was overriding that.
I'd rather let yarn/yarn-dedupe sort out SDR/STL requirements than yarn resolutions.  We bump those anyway
@W-15387805@

chore: remove resolutions so templates-beta ships

---

package.json

@W-14439471@
we might/should be able to bump to 20? since 18 is now in [maintenance](https://nodejs.org/en/about/previous-releases)

chore: bump required node to 18.6

---

.github/workflows/test.yml

don't globally install prm since it's not used (yarn install brings in the local equivalent)

ci: skip prm install after calling `yarn install`

---

theme.json

Plugins using `@oclif/core@v4` won't have colored JSON unless it's specified in the `theme.json` file. 
Colors were chosen based on the theme that oclif/core used to use: https://github.com/thlorenz/cardinal/blob/master/themes/jq.js

fix: add json theme

---

package.json

Temporarily remove oclif/core from pinnedDeps until PR is made to migrate to oclif/core v4

chore: temporarily remove oclif/core from pinnedDeps

---

src/util/env.ts

Just adds a missing `v` character.
n/a
n/a
n/a

fix(typo): fix `env` word

---

src/help/sfHelp.ts

Use `ux.colorize` to ensure proper and consistent TTY detection
@W-16198524@
https://github.com/forcedotcom/cli/issues/2951

fix: use ux.colorize

---

.github/workflows/promote.yml

Promote GHA tweaks

---

.github/workflows/promote-nightly-to-rc.yml
.github/workflows/promote-rc-to-latest.yml
.github/workflows/promote.yml
package.json
yarn.lock

When adding a new arch to oclif, promotions will fail if they do not exist. This allows you to pass in the new `--ignore-missing` flag. 
Related oclif work: https://github.com/oclif/oclif/pull/1567
[@W-16891787@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16891787)

Allow skipping oclif promote

---

.github/workflows/create-cli-release.yml
.github/workflows/promote-nightly-to-rc.yml
.github/workflows/promote-rc-to-latest.yml

Changes to support https://github.com/salesforcecli/plugin-release-management/pull/1218
[@W-16893140@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16893140)

Update GHAs to use new cli:version:inspect (with sfdx removed)

---

.github/workflows/just-nuts.yml

Adds plugin-data NUTs matrix
we had to split these because running them serially started to cause OOM issues with the new commands.

chore(ci): add plugin-data NUTs matrix

---

package.json

follow up to https://github.com/salesforcecli/cli/pull/2025
the linked PR above just patched 2.69.14 (that week's RC), so the option added was missed in today's RC.
Re-adding it back to `main` so new nightlies pick it up.
_How do you know this change is successful? What is the scope of this change? What tests test the criteria (or why no tests)?_
_The Acceptance Criteria can be copied from the work item if they exist there but it is useful to have on the PR when reviewing the code._

fix: disable deprecation warning

---

.github/workflows/just-nuts.yml
ARCHITECTURE.md
package.json

Removes `plugin-env` and `plugin-functions` from the JIT plugins list
@W-17668437@

chore: remove plugin-env/functions (JIT)

---

.github/workflows/just-nut.yml

Increases the retry timeout in an attempt to see this error less often when running NUTs:
`ConcurrentRequests (Concurrent API Requests) Limit exceeded`
[@W-18218507@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18218507)

W-18218507 increase retry timeout

---

.github/workflows/just-nuts.yml

plugin-agent needs a specific sandbox for the NUTs to work. Disabling this for now until we complete [@W-18398261@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18398261)

W-18398261: disable plugin-agent NUTs for now

---

.github/workflows/just-nuts.yml

Enables `plugin-agent` NUTs
These should pass now that this is merged https://github.com/salesforcecli/plugin-agent/pull/166
[@W-18838682@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18838682)

W-18838682 Enable plugin-agent nuts

---

.github/workflows/make-pr-for-nightly.yml

Fix the string comparison done in the nightly PR workflow that was blocking new nightly releases after the `2.100.0` RC, see copilot explanation below ⏬ 
_How do you know this change is successful? What is the scope of this change? What tests test the criteria (or why no tests)?_
_The Acceptance Criteria can be copied from the work item if they exist there but it is useful to have on the PR when reviewing the code._
Successfully created a 2.100.1 nightly from this branch:
https://github.com/salesforcecli/cli/actions/runs/16606422530/job/46979279048
docs:
https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#operators
🪄 fixed by copilot agent using sonnet 4, prompt:
```
// open file: cli/.github/workflows/make-pr-for-nightly.yml
this workflows isn't triggering none …
```

chore(ci): fix numerical comparison

---

.github/workflows/just-nuts.yml
package.json

`sfdx-scanner` is [deprecated](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/release-notes.html#code-analyzer-v4120-end-of-life). This PR removes the deprecated plugin from the Just In Time (JIT) list. 
[@W-19190281@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-19190281)
https://salesforce-internal.slack.com/archives/G0213NY8PMH/p1754069175598669

W-19190281: remove sfdx-scanner from JIT list

---

scripts/nsis.nsi

changes the custom nsis used in `sf` for checking for installed `sfdx` CLI to use the global cmd.exe instead of a local, possibly malicious cmd.exe file
oh boi - needs a windows machine
needs https://github.com/oclif/oclif/pull/1852
setup:
(I had to delete the JIT section in pjson in CLI for some steps to work locally)
1. be on windows
2. checkout the oclif PR / yarn / yarn build
3. checkout this PR / yarn / 
4. run `oclif pack:tarballs --xz --parallel --prune-lockfiles --targets win32-x64` or whatever windows target you need (just builds one, instead of every, installer)
5. `../path/to/oclif/bin/run.js pack:win --prune-lockfiles --targets win32-x64  --defender-exclusion unchecked`
6. If step 6 fails, there's a good chance it was at least able to build the `.nsi` file. I believe this file …

chore: change nsis script to use global cmd.exe @W-19315214@
